---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapplication
  labels:
    app: myapplication
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapplication
  template:
    metadata:
      labels:
        app: myapplication
    spec:
      containers:
      - name: myapplication
        image: hkkumar/k8snew:tagversion
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myapplication
spec:
  type: LoadBalancer
  selector:
    app: myapplication
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
