apiVersion: v1
kind: Node
metadata:
  annotations:
    container.googleapis.com/instance_id: "8887665395021789802"
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
#  creationTimestamp: "2020-03-07T11:27:04Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/fluentd-ds-ready: "true"
    beta.kubernetes.io/instance-type: n1-standard-1
    beta.kubernetes.io/os: linux
    cloud.google.com/gke-nodepool: default-pool
    cloud.google.com/gke-os-distribution: cos
    failure-domain.beta.kubernetes.io/region: europe-west1
    failure-domain.beta.kubernetes.io/zone: europe-west1-b
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: gke-k8s-cluster-demo-default-pool-308d617d-8m0d
    kubernetes.io/os: linux
  name: gke-k8s-cluster-demo-default-pool-308d617d-8m0d
  resourceVersion: "9109"
  selfLink: /api/v1/nodes/gke-k8s-cluster-demo-default-pool-308d617d-8m0d
  uid: 92708edc-6066-11ea-b0b4-42010a8401b1
spec:
  podCIDR: 10.28.2.0/24
  providerID: gce://peak-radius-261019/europe-west1-b/gke-k8s-cluster-demo-default-pool-308d617d-8m0d
status:
  addresses:
  - address: 10.132.0.27
    type: InternalIP
  - address: 35.205.164.151
    type: ExternalIP
  - address: gke-k8s-cluster-demo-default-pool-308d617d-8m0d.europe-west1-b.c.peak-radius-261019.internal
    type: InternalDNS
  - address: gke-k8s-cluster-demo-default-pool-308d617d-8m0d.europe-west1-b.c.peak-radius-261019.internal
    type: Hostname
  allocatable:
    attachable-volumes-gce-pd: "127"
    cpu: 940m
    ephemeral-storage: "47093746742"
    hugepages-2Mi: "0"
    memory: 2701244Ki
    pods: "110"
  capacity:
    attachable-volumes-gce-pd: "127"
    cpu: "1"
    ephemeral-storage: 98868448Ki
    hugepages-2Mi: "0"
    memory: 3786684Ki
    pods: "110"
  conditions:
  - lastHeartbeatTime: "2020-03-07T12:06:34Z"
    lastTransitionTime: "2020-03-07T11:27:08Z"
    message: kernel has no deadlock
    reason: KernelHasNoDeadlock
    status: "False"
    type: KernelDeadlock
  - lastHeartbeatTime: "2020-03-07T12:06:34Z"
    lastTransitionTime: "2020-03-07T11:27:08Z"
    message: Filesystem is not read-only
    reason: FilesystemIsNotReadOnly
    status: "False"
    type: ReadonlyFilesystem
  - lastHeartbeatTime: "2020-03-07T12:06:34Z"
    lastTransitionTime: "2020-03-07T11:27:07Z"
    message: docker overlay2 is functioning properly
    reason: NoCorruptDockerOverlay2
    status: "False"
    type: CorruptDockerOverlay2
  - lastHeartbeatTime: "2020-03-07T12:06:34Z"
    lastTransitionTime: "2020-03-07T11:27:07Z"
    message: node is functioning properly
    reason: NoFrequentUnregisterNetDevice
    status: "False"
    type: FrequentUnregisterNetDevice
  - lastHeartbeatTime: "2020-03-07T12:06:34Z"
    lastTransitionTime: "2020-03-07T11:27:07Z"
    message: kubelet is functioning properly
    reason: NoFrequentKubeletRestart
    status: "False"
    type: FrequentKubeletRestart
  - lastHeartbeatTime: "2020-03-07T12:06:34Z"
    lastTransitionTime: "2020-03-07T11:27:07Z"
    message: docker is functioning properly
    reason: NoFrequentDockerRestart
    status: "False"
    type: FrequentDockerRestart
  - lastHeartbeatTime: "2020-03-07T12:06:34Z"
    lastTransitionTime: "2020-03-07T11:27:07Z"
    message: containerd is functioning properly
    reason: NoFrequentContainerdRestart
    status: "False"
    type: FrequentContainerdRestart
  - lastHeartbeatTime: "2020-03-07T11:27:06Z"
    lastTransitionTime: "2020-03-07T11:27:06Z"
    message: NodeController create implicit route
    reason: RouteCreated
    status: "False"
    type: NetworkUnavailable
  - lastHeartbeatTime: "2020-03-07T12:06:38Z"
    lastTransitionTime: "2020-03-07T11:27:04Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2020-03-07T12:06:38Z"
    lastTransitionTime: "2020-03-07T11:27:04Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2020-03-07T12:06:38Z"
    lastTransitionTime: "2020-03-07T11:27:04Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2020-03-07T12:06:38Z"
    lastTransitionTime: "2020-03-07T11:27:05Z"
    message: kubelet is posting ready status. AppArmor enabled
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - gcr.io/stackdriver-agents/stackdriver-logging-agent@sha256:79ddc530f0e558da80c3857c2e02d8b6dcce64c4c875fb94e3a420f53c502492
    - gcr.io/stackdriver-agents/stackdriver-logging-agent:1.6.17-16060
    sizeBytes: 413364992
  - names:
    - nginx@sha256:7224f0a40f2110889889f47dcafa972a8658b7bdd3b50cfa12fd5f80364cbcfe
    - nginx:1.10.0
    sizeBytes: 182773691
  - names:
    - k8s.gcr.io/fluentd-elasticsearch@sha256:5a704c386f66bb3c24e3bcf2e94269c426f1473100fcd37b31579ca8b709c558
    - k8s.gcr.io/fluentd-elasticsearch:v2.4.0
    sizeBytes: 139904122
  - names:
    - k8s.gcr.io/kubernetes-dashboard-amd64@sha256:0ae6b69432e78069c5ce2bcde0fe409c5c4d6f0f4d9cd50a17974fea38898747
    - k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1
    sizeBytes: 121711221
  - names:
    - k8s.gcr.io/node-problem-detector@sha256:9d54df11804a862c54276648702a45a6a0027a9d930a86becd69c34cc84bf510
    - k8s.gcr.io/node-problem-detector:v0.6.3
    sizeBytes: 93550819
  - names:
    - k8s.gcr.io/fluentd-gcp-scaler@sha256:4f28f10fb89506768910b858f7a18ffb996824a16d70d5ac895e49687df9ff58
    - k8s.gcr.io/fluentd-gcp-scaler:0.5.2
    sizeBytes: 90498960
  - names:
    - gke.gcr.io/heapster@sha256:26891d2f8c22407a772b911aed912993e1c530128ebb2d3561b49fc16a52d765
    - gke.gcr.io/heapster:v1.7.2
    sizeBytes: 84338494
  - names:
    - gke.gcr.io/kube-proxy:v1.14.10-gke.17
    - k8s.gcr.io/kube-proxy:v1.14.10-gke.17
    sizeBytes: 83623316
  - names:
    - k8s.gcr.io/kube-addon-manager@sha256:382c220b3531d9f95bf316a16b7282cc2ef929cd8a89a9dd3f5933edafc41a8e
    - k8s.gcr.io/kube-addon-manager:v9.0.1
    sizeBytes: 83076194
  - names:
    - gcr.io/stackdriver-agents/metadata-agent-go@sha256:ca13ec92f6e41befff6ca2a578ee7951edb1e49a566430f816f9a8acf631a62a
    - gcr.io/stackdriver-agents/metadata-agent-go:1.0.5
    sizeBytes: 82131866
  - names:
    - k8s.gcr.io/heapster-amd64@sha256:9fae0af136ce0cf4f88393b3670f7139ffc464692060c374d2ae748e13144521
    - k8s.gcr.io/heapster-amd64:v1.6.0-beta.1
    sizeBytes: 76016169
  - names:
    - k8s.gcr.io/ingress-gce-glbc-amd64@sha256:14f14351a03038b238232e60850a9cfa0dffbed0590321ef84216a432accc1ca
    - k8s.gcr.io/ingress-gce-glbc-amd64:v1.2.3
    sizeBytes: 71797285
  - names:
    - k8s.gcr.io/k8s-dns-node-cache@sha256:c67f04ac8b9d30b96eeedc47008e5af403e8ab42d139796de3b03865ab99940b
    - k8s.gcr.io/k8s-dns-node-cache:1.15.2
    sizeBytes: 62530777
  - names:
    - asia.gcr.io/gke-release-staging/cpvpa-amd64@sha256:5e56182e651b57d4c2f861214e32ec9fac063694d7222c59ee915203bdfb5181
    - eu.gcr.io/gke-release-staging/cpvpa-amd64@sha256:5e56182e651b57d4c2f861214e32ec9fac063694d7222c59ee915203bdfb5181
    - gcr.io/gke-release-staging/cpvpa-amd64@sha256:5e56182e651b57d4c2f861214e32ec9fac063694d7222c59ee915203bdfb5181
    - asia.gcr.io/gke-release-staging/cpvpa-amd64:v0.7.1-gke.0
    - eu.gcr.io/gke-release-staging/cpvpa-amd64:v0.7.1-gke.0
    sizeBytes: 53154431
  - names:
    - asia.gcr.io/gke-release-staging/addon-resizer@sha256:94e7e68175dfd18a9e3c31bc1f4a6ab19444efef47192f13b0e5af3b03dc04c6
    - eu.gcr.io/gke-release-staging/addon-resizer@sha256:94e7e68175dfd18a9e3c31bc1f4a6ab19444efef47192f13b0e5af3b03dc04c6
    - gcr.io/gke-release-staging/addon-resizer@sha256:94e7e68175dfd18a9e3c31bc1f4a6ab19444efef47192f13b0e5af3b03dc04c6
    - asia.gcr.io/gke-release-staging/addon-resizer:1.8.4-gke.0
    - eu.gcr.io/gke-release-staging/addon-resizer:1.8.4-gke.0
    sizeBytes: 52732803
  - names:
    - k8s.gcr.io/k8s-dns-kube-dns@sha256:c54a527a4ba8f1bc15e4796b09bf5d69313c7f42af9911dc437e056c0264a2fe
    - k8s.gcr.io/k8s-dns-kube-dns:1.14.13
    sizeBytes: 51157394
  - names:
    - k8s.gcr.io/ip-masq-agent-amd64@sha256:eb43b4cdc43a50260b82fdd63208e0b2d401ec830b486d0c7a570a6d73854451
    - k8s.gcr.io/ip-masq-agent-amd64:v2.4.1
    sizeBytes: 50144412
  - names:
    - k8s.gcr.io/event-exporter@sha256:06acf489ab092b4fb49273e426549a52c0fcd1dbcb67e03d5935b5ee1a899c3e
    - k8s.gcr.io/event-exporter:v0.2.5
    sizeBytes: 47261019
  - names:
    - k8s.gcr.io/event-exporter@sha256:16ca66e2b5dc7a1ce6a5aafcb21d0885828b75cdfc08135430480f7ad2364adc
    - k8s.gcr.io/event-exporter:v0.2.4
    sizeBytes: 47261019
  - names:
    - asia.gcr.io/gke-release-staging/cluster-proportional-autoscaler-amd64@sha256:e3f48b3d1e49cfa3e7f002020769c9cd01cd0e77bbc99dc133c7ab0f8097e989
    - eu.gcr.io/gke-release-staging/cluster-proportional-autoscaler-amd64@sha256:e3f48b3d1e49cfa3e7f002020769c9cd01cd0e77bbc99dc133c7ab0f8097e989
    - gcr.io/gke-release-staging/cluster-proportional-autoscaler-amd64@sha256:e3f48b3d1e49cfa3e7f002020769c9cd01cd0e77bbc99dc133c7ab0f8097e989
    - asia.gcr.io/gke-release-staging/cluster-proportional-autoscaler-amd64:1.7.1-gke.0
    - eu.gcr.io/gke-release-staging/cluster-proportional-autoscaler-amd64:1.7.1-gke.0
    sizeBytes: 43947291
  - names:
    - k8s.gcr.io/k8s-dns-sidecar@sha256:c4f36a12fa297c48cb80779c89f6a58818d1fa7edccb08bc67d79acacc3871d7
    - k8s.gcr.io/k8s-dns-sidecar:1.14.13
    sizeBytes: 42852039
  - names:
    - k8s.gcr.io/gke-node-termination-handler@sha256:e08ca863a547754fa7b75064bdad04f04cbef86c7b0a181ecc7304e747623181
    sizeBytes: 42465304
  - names:
    - k8s.gcr.io/prometheus-to-sd@sha256:14666989f40bb7c896c3e775a93c6873e2b791d65bc65579f58a078b7f9a764e
    - k8s.gcr.io/prometheus-to-sd:v0.5.0
    sizeBytes: 41861013
  - names:
    - k8s.gcr.io/k8s-dns-dnsmasq-nanny@sha256:096e2285e5aaa2ce38532993d8bfd95da92e9b73fc75e9078e18891caf6a220e
    - k8s.gcr.io/k8s-dns-dnsmasq-nanny:1.14.13
    sizeBytes: 41372492
  - names:
    - k8s.gcr.io/metrics-server-amd64@sha256:78938f933822856f443e6827fe5b37d6cc2f74ae888ac8b33d06fdbe5f8c658b
    - k8s.gcr.io/metrics-server-amd64:v0.3.1
    sizeBytes: 40767713
#  nodeInfo:
#    architecture: amd64
#    bootID: e05c0d63-521d-4287-a4ec-40f040c0f259
#    containerRuntimeVersion: docker://18.9.7
#    kernelVersion: 4.14.138+
#    kubeProxyVersion: v1.14.10-gke.17
#    kubeletVersion: v1.14.10-gke.17
#    machineID: 159b91aa73f8d2b56a34e9e67e95f44d
#    operatingSystem: linux
#    osImage: Container-Optimized OS from Google
#    systemUUID: 159B91AA-73F8-D2B5-6A34-E9E67E95F44D
