apiVersion: v1
kind: Node
metadata:
  annotations:
    container.googleapis.com/instance_id: "135493253843591182"
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2020-03-06T19:07:28Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/fluentd-ds-ready: "true"
    beta.kubernetes.io/instance-type: n1-standard-1
    beta.kubernetes.io/os: linux
    cloud.google.com/gke-nodepool: default-pool
    cloud.google.com/gke-os-distribution: cos
    failure-domain.beta.kubernetes.io/region: us-central1
    failure-domain.beta.kubernetes.io/zone: us-central1-c
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: gke-k8s-cluster-demo-default-pool-5b9c96b3-slz1
    kubernetes.io/os: linux
  name: gke-k8s-cluster-demo-default-pool-5b9c96b3-slz1
  resourceVersion: "46774"
  selfLink: /api/v1/nodes/gke-k8s-cluster-demo-default-pool-5b9c96b3-slz1
  uid: b8be594a-5fdd-11ea-b159-42010a800fed
spec:
  podCIDR: 10.40.1.0/24
  providerID: gce://peak-radius-261019/us-central1-c/gke-k8s-cluster-demo-default-pool-5b9c96b3-slz1
status:
  addresses:
  - address: 10.128.0.4
    type: InternalIP
  - address: 35.238.81.73
    type: ExternalIP
  - address: gke-k8s-cluster-demo-default-pool-5b9c96b3-slz1.us-central1-c.c.peak-radius-261019.internal
    type: InternalDNS
  - address: gke-k8s-cluster-demo-default-pool-5b9c96b3-slz1.us-central1-c.c.peak-radius-261019.internal
    type: Hostname
  allocatable:
    attachable-volumes-gce-pd: "127"
    cpu: 940m
    ephemeral-storage: "47093746742"
    hugepages-2Mi: "0"
    memory: 2701244Ki
    pods: "110"
  capacity:
    attachable-volumes-gce-pd: "127"
    cpu: "1"
    ephemeral-storage: 98868448Ki
    hugepages-2Mi: "0"
    memory: 3786684Ki
    pods: "110"
  conditions:
  - lastHeartbeatTime: "2020-03-06T22:44:26Z"
    lastTransitionTime: "2020-03-06T19:07:29Z"
    message: docker overlay2 is functioning properly
    reason: NoCorruptDockerOverlay2
    status: "False"
    type: CorruptDockerOverlay2
  - lastHeartbeatTime: "2020-03-06T22:44:26Z"
    lastTransitionTime: "2020-03-06T19:07:29Z"
    message: node is functioning properly
    reason: NoFrequentUnregisterNetDevice
    status: "False"
    type: FrequentUnregisterNetDevice
  - lastHeartbeatTime: "2020-03-06T22:44:26Z"
    lastTransitionTime: "2020-03-06T19:07:29Z"
    message: kubelet is functioning properly
    reason: NoFrequentKubeletRestart
    status: "False"
    type: FrequentKubeletRestart
  - lastHeartbeatTime: "2020-03-06T22:44:26Z"
    lastTransitionTime: "2020-03-06T19:07:29Z"
    message: docker is functioning properly
    reason: NoFrequentDockerRestart
    status: "False"
    type: FrequentDockerRestart
  - lastHeartbeatTime: "2020-03-06T22:44:26Z"
    lastTransitionTime: "2020-03-06T19:07:29Z"
    message: containerd is functioning properly
    reason: NoFrequentContainerdRestart
    status: "False"
    type: FrequentContainerdRestart
  - lastHeartbeatTime: "2020-03-06T22:44:26Z"
    lastTransitionTime: "2020-03-06T19:07:29Z"
    message: kernel has no deadlock
    reason: KernelHasNoDeadlock
    status: "False"
    type: KernelDeadlock
  - lastHeartbeatTime: "2020-03-06T22:44:26Z"
    lastTransitionTime: "2020-03-06T19:07:29Z"
    message: Filesystem is not read-only
    reason: FilesystemIsNotReadOnly
    status: "False"
    type: ReadonlyFilesystem
  - lastHeartbeatTime: "2020-03-06T19:07:29Z"
    lastTransitionTime: "2020-03-06T19:07:29Z"
    message: NodeController create implicit route
    reason: RouteCreated
    status: "False"
    type: NetworkUnavailable
  - lastHeartbeatTime: "2020-03-06T22:44:50Z"
    lastTransitionTime: "2020-03-06T19:07:27Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2020-03-06T22:44:50Z"
    lastTransitionTime: "2020-03-06T19:07:27Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2020-03-06T22:44:50Z"
    lastTransitionTime: "2020-03-06T19:07:27Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2020-03-06T22:44:50Z"
    lastTransitionTime: "2020-03-06T19:07:28Z"
    message: kubelet is posting ready status. AppArmor enabled
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - gcr.io/stackdriver-agents/stackdriver-logging-agent@sha256:79ddc530f0e558da80c3857c2e02d8b6dcce64c4c875fb94e3a420f53c502492
    - gcr.io/stackdriver-agents/stackdriver-logging-agent:1.6.17-16060
    sizeBytes: 413364992
  - names:
    - k8s.gcr.io/fluentd-elasticsearch@sha256:5a704c386f66bb3c24e3bcf2e94269c426f1473100fcd37b31579ca8b709c558
    - k8s.gcr.io/fluentd-elasticsearch:v2.4.0
    sizeBytes: 139904122
  - names:
    - k8s.gcr.io/kubernetes-dashboard-amd64@sha256:0ae6b69432e78069c5ce2bcde0fe409c5c4d6f0f4d9cd50a17974fea38898747
    - k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1
    sizeBytes: 121711221
  - names:
    - hkkumar/tomcat333@sha256:de70bf4f5552523018133fa26d7713383f743838d869d92ef8f92571543b4ac8
    - hkkumar/tomcat333:latest
    sizeBytes: 108857292
  - names:
    - k8s.gcr.io/node-problem-detector@sha256:9d54df11804a862c54276648702a45a6a0027a9d930a86becd69c34cc84bf510
    - k8s.gcr.io/node-problem-detector:v0.6.3
    sizeBytes: 93550819
  - names:
    - k8s.gcr.io/fluentd-gcp-scaler@sha256:4f28f10fb89506768910b858f7a18ffb996824a16d70d5ac895e49687df9ff58
    - k8s.gcr.io/fluentd-gcp-scaler:0.5.2
    sizeBytes: 90498960
  - names:
    - k8s.gcr.io/k8s-dns-kube-dns-amd64@sha256:a13c60e2a9d49f965095a1e003388926f3f2a6189ed4aecb1541f114c955f8ec
    - k8s.gcr.io/k8s-dns-kube-dns-amd64:1.15.4
    sizeBytes: 86980681
  - names:
    - gke.gcr.io/heapster@sha256:26891d2f8c22407a772b911aed912993e1c530128ebb2d3561b49fc16a52d765
    - gke.gcr.io/heapster:v1.7.2
    sizeBytes: 84338494
  - names:
    - gke.gcr.io/kube-proxy:v1.14.10-gke.17
    - k8s.gcr.io/kube-proxy:v1.14.10-gke.17
    sizeBytes: 83623316
  - names:
    - k8s.gcr.io/kube-addon-manager@sha256:382c220b3531d9f95bf316a16b7282cc2ef929cd8a89a9dd3f5933edafc41a8e
    - k8s.gcr.io/kube-addon-manager:v9.0.1
    sizeBytes: 83076194
  - names:
    - k8s.gcr.io/k8s-dns-sidecar-amd64@sha256:e55cbd5361a86bf0a01bfeaca2e958e15571f1e741356eab83bb444a13020d4c
    - k8s.gcr.io/k8s-dns-sidecar-amd64:1.15.4
    sizeBytes: 79319492
  - names:
    - k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64@sha256:0a70a8a9ae8cfe752021de84f13b3ecd109d9b5fbe3f1541c52fcd1d4c2c0b45
    - k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.15.4
    sizeBytes: 77756591
  - names:
    - k8s.gcr.io/heapster-amd64@sha256:9fae0af136ce0cf4f88393b3670f7139ffc464692060c374d2ae748e13144521
    - k8s.gcr.io/heapster-amd64:v1.6.0-beta.1
    sizeBytes: 76016169
  - names:
    - k8s.gcr.io/ingress-gce-glbc-amd64@sha256:14f14351a03038b238232e60850a9cfa0dffbed0590321ef84216a432accc1ca
    - k8s.gcr.io/ingress-gce-glbc-amd64:v1.2.3
    sizeBytes: 71797285
  - names:
    - k8s.gcr.io/k8s-dns-node-cache@sha256:c67f04ac8b9d30b96eeedc47008e5af403e8ab42d139796de3b03865ab99940b
    - k8s.gcr.io/k8s-dns-node-cache:1.15.2
    sizeBytes: 62530777
  - names:
    - asia.gcr.io/gke-release-staging/cpvpa-amd64@sha256:5e56182e651b57d4c2f861214e32ec9fac063694d7222c59ee915203bdfb5181
    - eu.gcr.io/gke-release-staging/cpvpa-amd64@sha256:5e56182e651b57d4c2f861214e32ec9fac063694d7222c59ee915203bdfb5181
    - gcr.io/gke-release-staging/cpvpa-amd64@sha256:5e56182e651b57d4c2f861214e32ec9fac063694d7222c59ee915203bdfb5181
    - asia.gcr.io/gke-release-staging/cpvpa-amd64:v0.7.1-gke.0
    - eu.gcr.io/gke-release-staging/cpvpa-amd64:v0.7.1-gke.0
    sizeBytes: 53154431
  - names:
    - asia.gcr.io/gke-release-staging/addon-resizer@sha256:94e7e68175dfd18a9e3c31bc1f4a6ab19444efef47192f13b0e5af3b03dc04c6
    - eu.gcr.io/gke-release-staging/addon-resizer@sha256:94e7e68175dfd18a9e3c31bc1f4a6ab19444efef47192f13b0e5af3b03dc04c6
    - gcr.io/gke-release-staging/addon-resizer@sha256:94e7e68175dfd18a9e3c31bc1f4a6ab19444efef47192f13b0e5af3b03dc04c6
    - asia.gcr.io/gke-release-staging/addon-resizer:1.8.4-gke.0
    - eu.gcr.io/gke-release-staging/addon-resizer:1.8.4-gke.0
    sizeBytes: 52732803
  - names:
    - k8s.gcr.io/k8s-dns-kube-dns@sha256:c54a527a4ba8f1bc15e4796b09bf5d69313c7f42af9911dc437e056c0264a2fe
    - k8s.gcr.io/k8s-dns-kube-dns:1.14.13
    sizeBytes: 51157394
  - names:
    - k8s.gcr.io/ip-masq-agent-amd64@sha256:eb43b4cdc43a50260b82fdd63208e0b2d401ec830b486d0c7a570a6d73854451
    - k8s.gcr.io/ip-masq-agent-amd64:v2.4.1
    sizeBytes: 50144412
  - names:
    - k8s.gcr.io/event-exporter@sha256:16ca66e2b5dc7a1ce6a5aafcb21d0885828b75cdfc08135430480f7ad2364adc
    - k8s.gcr.io/event-exporter:v0.2.4
    sizeBytes: 47261019
  - names:
    - asia.gcr.io/gke-release-staging/cluster-proportional-autoscaler-amd64@sha256:e3f48b3d1e49cfa3e7f002020769c9cd01cd0e77bbc99dc133c7ab0f8097e989
    - eu.gcr.io/gke-release-staging/cluster-proportional-autoscaler-amd64@sha256:e3f48b3d1e49cfa3e7f002020769c9cd01cd0e77bbc99dc133c7ab0f8097e989
    - gcr.io/gke-release-staging/cluster-proportional-autoscaler-amd64@sha256:e3f48b3d1e49cfa3e7f002020769c9cd01cd0e77bbc99dc133c7ab0f8097e989
    - asia.gcr.io/gke-release-staging/cluster-proportional-autoscaler-amd64:1.7.1-gke.0
    - eu.gcr.io/gke-release-staging/cluster-proportional-autoscaler-amd64:1.7.1-gke.0
    sizeBytes: 43947291
  - names:
    - k8s.gcr.io/k8s-dns-sidecar@sha256:c4f36a12fa297c48cb80779c89f6a58818d1fa7edccb08bc67d79acacc3871d7
    - k8s.gcr.io/k8s-dns-sidecar:1.14.13
    sizeBytes: 42852039
  - names:
    - k8s.gcr.io/gke-node-termination-handler@sha256:e08ca863a547754fa7b75064bdad04f04cbef86c7b0a181ecc7304e747623181
    sizeBytes: 42465304
  - names:
    - k8s.gcr.io/prometheus-to-sd@sha256:aca8ef83a7fae83f1f8583e978dd4d1ff655b9f2ca0a76bda5edce6d8965bdf2
    - k8s.gcr.io/prometheus-to-sd:v0.4.2
    sizeBytes: 41861013
  - names:
    - k8s.gcr.io/prometheus-to-sd@sha256:14666989f40bb7c896c3e775a93c6873e2b791d65bc65579f58a078b7f9a764e
    - k8s.gcr.io/prometheus-to-sd:v0.5.0
    sizeBytes: 41861013
  nodeInfo:
    architecture: amd64
    bootID: 5aace252-1be1-42e6-8721-8e9d85a5fa09
    containerRuntimeVersion: docker://18.9.7
    kernelVersion: 4.14.138+
    kubeProxyVersion: v1.14.10-gke.17
    kubeletVersion: v1.14.10-gke.17
    machineID: b9ee0220ed3f8876c448dffcab9430b9
    operatingSystem: linux
    osImage: Container-Optimized OS from Google
    systemUUID: B9EE0220-ED3F-8876-C448-DFFCAB9430B9
